### ISSUE TITLE
Wrong activity theme

### ISSUE THREAD

**Issue by mschoettle** [googlesamples/android-LNotifications#3]
When running this example in the emulator the application crashes during startup with the following exception (using a device with API 26):

```
[...]
Caused by: java.lang.IllegalArgumentException: You need to use a Theme.AppCompat theme (or descendant) with the design library.
                                                     at android.support.design.widget.ThemeUtils.checkAppCompatTheme(ThemeUtils.java:33)
                                                     at android.support.design.widget.TabLayout.<init>(TabLayout.java:298)
[...]
```

To fix it, I had to change the theme in res/values/base-template-styles.xml from `android:Theme.Material.Light` to `Theme.AppCompat.Light`.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
